In [43]:
import pandas_datareader.data as web
import pandas as pd
import datetime as dt

## Data
###### We are going to get Stock information for the following Indexes:

* FTSE 100(UK)
* S&P 500(USA)
* Dow Jones Industrial Average(USA) 
* NASDAQ Composite(USA)
* Hang Seng Index(CHINA)
* Nikkei 225(JAPAN)
* CAC 40(FRANCE)
* IBEX 35 Index(SPAIN)
* FTSE MIB Index(ITALY)
* Austrian Traded Index in EUR(AUSTRIA)

In [7]:
df = web.DataReader('\^FTSE','yahoo')

In [10]:
df1 = web.DataReader('^GSPC','yahoo')

In [13]:
df2 = web.DataReader('^DJI','yahoo')

In [16]:
df3 = web.DataReader('^IXIC','yahoo')

In [37]:
df4 = web.DataReader('^HSI','yahoo')

In [38]:
df8 = web.DataReader('^N225','yahoo')

In [23]:
df5 = web.DataReader('^FCHI','yahoo')

In [27]:
df6 = web.DataReader('^IBEX','yahoo')

In [31]:
df7 = web.DataReader('\FTSEMIB.MI','yahoo')

In [40]:
df9 = web.DataReader('^ATX','yahoo')

In [49]:
start = dt.datetime(2009,11,1)

In [50]:
end = dt.datetime(2019,11,1)

In [51]:
df10 = web.DataReader(['\^FTSE','^GSPC','^DJI','^IXIC','^HSI','^N225','^FCHI','^IBEX','\FTSEMIB.MI','^ATX'],'yahoo',start,end)

In [53]:
df10.tail()

Attributes    Adj Close                                                        \
Symbols          \^FTSE        ^GSPC          ^DJI        ^IXIC          ^HSI
Date
2019-10-28  7331.299805  3039.419922  27090.720703  8325.990234  26891.259766
2019-10-29  7306.299805  3036.889893  27071.460938  8276.849609  26786.759766
2019-10-30  7330.799805  3046.770020  27186.689453  8303.980469  26667.710938
2019-10-31  7248.399902  3037.560059  27046.230469  8292.360352  26906.720703
2019-11-01  7302.399902  3066.909912  27347.359375  8386.400391  27100.759766

Attributes                                                                   \
Symbols            ^N225        ^FCHI        ^IBEX \FTSEMIB.MI         ^ATX
Date
2019-10-28  22867.269531  5730.569824  9433.000000     22696.0  3189.370117
2019-10-29  22974.130859  5740.140137  9400.099609     22681.0  3190.520020
2019-10-30  22843.119141  5765.870117  9284.500000     22646.0  3171.209961
2019-10-31  22927.039062  5729.859863  9257.500000     22694.0  3139.590088
2019-11-01  22850.769531  5761.890137  9328.000000     22934.0  3164.639893

Attributes  ...       Volume                                           \
Symbols     ...       \^FTSE         ^GSPC         ^DJI         ^IXIC
Date        ...
2019-10-28  ...  676041800.0  3.524970e+09  290770000.0  1.959920e+09
2019-10-29  ...  710020700.0  3.594430e+09  269610000.0  1.842720e+09
2019-10-30  ...  672191900.0  3.779660e+09  231750000.0  1.936060e+09
2019-10-31  ...  847657500.0  4.149310e+09  273830000.0  2.276140e+09
2019-11-01  ...  582078600.0  3.956290e+09  270870000.0  2.071350e+09

Attributes                                                                    \
Symbols             ^HSI        ^N225        ^FCHI        ^IBEX  \FTSEMIB.MI
Date
2019-10-28  1.476176e+09   48100000.0   69809000.0  123721700.0  272005000.0
2019-10-29  1.515349e+09   72900000.0   74571800.0  155531300.0  327253200.0
2019-10-30  1.554112e+09  101600000.0   90959100.0  192868000.0  440251100.0
2019-10-31  1.907594e+09   78300000.0  112062300.0  227115200.0  435498500.0
2019-11-01  1.421452e+09   65400000.0   65867300.0  160721600.0  289466200.0

Attributes
Symbols          ^ATX
Date
2019-10-28  3080900.0
2019-10-29  3391000.0
2019-10-30  3018600.0
2019-10-31  3871800.0
2019-11-01  2795300.0

[5 rows x 60 columns]

In [54]:
df10.head()

Attributes    Adj Close                                                        \
Symbols          \^FTSE        ^GSPC          ^DJI        ^IXIC          ^HSI
Date
2009-11-02  5104.500000  1042.880005   9789.440430  2049.199951  21620.189453
2009-11-03  5037.200195  1045.410034   9771.910156  2057.320068  21240.060547
2009-11-04  5107.899902  1046.500000   9802.139648  2055.520020  21614.769531
2009-11-05  5125.600098  1066.630005  10005.959961  2105.320068  21479.080078
2009-11-06  5142.700195  1069.300049  10023.419922  2112.439941  21829.720703

Attributes                                                                   \
Symbols           ^N225        ^FCHI         ^IBEX \FTSEMIB.MI         ^ATX
Date
2009-11-02  9802.950195  3639.459961  11465.788086     22298.0  2525.840088
2009-11-03          NaN  3584.250000  11242.388672     21947.0  2460.100098
2009-11-04  9844.309570  3670.330078  11387.688477     22386.0  2526.879883
2009-11-05  9717.440430  3708.729980  11548.888672     22582.0  2561.739990
2009-11-06  9789.349609  3707.290039  11580.587891     22550.0  2561.120117

Attributes  ...        Volume                                           \
Symbols     ...        \^FTSE         ^GSPC         ^DJI         ^IXIC
Date        ...
2009-11-02  ...  1.039675e+09  6.202640e+09  242460000.0  2.408320e+09
2009-11-03  ...  1.355407e+09  5.487500e+09  231520000.0  2.061050e+09
2009-11-04  ...  9.595497e+08  5.635510e+09  224130000.0  2.217520e+09
2009-11-05  ...  1.004108e+09  4.848350e+09  211040000.0  2.209690e+09
2009-11-06  ...  1.026864e+09  4.277130e+09  181010000.0  1.829150e+09

Attributes                                                                 \
Symbols             ^HSI        ^N225        ^FCHI     ^IBEX  \FTSEMIB.MI
Date
2009-11-02  1.722584e+09  128500000.0  151752000.0  156200.0  669310100.0
2009-11-03  1.458859e+09          NaN  156080000.0  215400.0  647856600.0
2009-11-04  1.403161e+09  119300000.0  155873400.0  166800.0  610298000.0
2009-11-05  1.261955e+09  147100000.0  138739600.0  180000.0  767510600.0
2009-11-06  1.524135e+09  141500000.0  131920100.0  188600.0  648486000.0

Attributes
Symbols          ^ATX
Date
2009-11-02  6783800.0
2009-11-03  6496200.0
2009-11-04  5143600.0
2009-11-05  6182600.0
2009-11-06  7663400.0

[5 rows x 60 columns]

In [55]:
df10.describe()

Attributes    Adj Close                                                        \
Symbols          \^FTSE        ^GSPC          ^DJI        ^IXIC          ^HSI
count       2527.000000  2518.000000   2518.000000  2518.000000   2465.000000
mean        6479.776808  1929.456175  17320.312924  4639.280898  23671.238719
std          724.545418   579.365897   5054.960949  1838.906262   3175.614530
min         4805.799805  1022.580017   9686.480469  2049.199951  16250.269531
25%         5868.800049  1360.664978  12837.330078  2927.862488  21424.789062
50%         6568.399902  1964.630005  16845.005859  4533.080078  23064.560547
75%         7093.850098  2388.540100  20951.127930  6074.642334  25701.630859
max         7877.500000  3066.909912  27359.160156  8386.400391  33154.121094

Attributes                                                         \
Symbols            ^N225        ^FCHI         ^IBEX   \FTSEMIB.MI
count        2448.000000  2556.000000   2556.000000   2539.000000
mean        15562.144354  4380.772215   9554.323529  19596.842852
std          4886.293667   733.977456   1144.671934   2722.305601
min          8160.009766  2781.679932   5956.293945  12363.000000
25%         10144.802246  3805.142456   8704.193359  17282.500000
50%         15864.819824  4345.489990   9653.845215  20330.000000
75%         20003.032715  5059.109863  10415.992188  21797.000000
max         24270.619141  5765.870117  12222.487305  24544.000000

Attributes               ...        Volume                              \
Symbols            ^ATX  ...        \^FTSE         ^GSPC          ^DJI
count       2469.000000  ...  2.527000e+03  2.518000e+03  2.518000e+03
mean        2603.052300  ...  8.042278e+08  3.730362e+09  1.887217e+08
std          421.296514  ...  2.560425e+08  8.218007e+08  1.104343e+08
min         1652.790039  ...  6.676710e+07  1.025000e+09  8.410000e+06
25%         2290.379883  ...  6.556055e+08  3.246178e+09  1.027450e+08
50%         2510.189941  ...  7.688576e+08  3.604330e+09  1.510050e+08
75%         2902.429932  ...  8.936904e+08  4.093735e+09  2.565300e+08
max         3688.780029  ...  3.761301e+09  1.061781e+10  9.005100e+08

Attributes                                                          \
Symbols            ^IXIC          ^HSI         ^N225         ^FCHI
count       2.518000e+03  2.465000e+03  2.448000e+03  2.556000e+03
mean        1.965829e+09  1.737409e+09  1.324671e+08  1.159998e+08
std         3.980213e+08  6.258564e+08  5.602263e+07  4.663436e+07
min         2.214300e+08  5.101898e+08  0.000000e+00  0.000000e+00
25%         1.736938e+09  1.349937e+09  9.757500e+07  8.400495e+07
50%         1.911695e+09  1.619496e+09  1.265000e+08  1.069892e+08
75%         2.139560e+09  1.958325e+09  1.567000e+08  1.387481e+08
max         4.571670e+09  9.527773e+09  5.952000e+08  4.385013e+08

Attributes
Symbols            ^IBEX   \FTSEMIB.MI          ^ATX
count       2.556000e+03  2.539000e+03  2.469000e+03
mean        2.127222e+08  6.894857e+08  6.008080e+06
std         1.054282e+08  3.388907e+08  3.261288e+06
min         0.000000e+00  0.000000e+00  0.000000e+00
25%         1.535348e+08  4.495530e+08  4.156400e+06
50%         2.081134e+08  6.509373e+08  5.418500e+06
75%         2.733725e+08  8.688308e+08  6.987400e+06
max         7.894902e+08  2.676921e+09  8.234560e+07

[8 rows x 60 columns]